### ISSUE TITLE
Only takes effect when `Neovim` is just opened

### ISSUE THREAD

**Issue by guxuerui** [razak17/tailwind-fold.nvim#1]
Hello~  Based on my test, this plugin only takes effect when `Neovim` is just opened, then if I open an other file example `test.vue`, it hasn't taken effect. 
So is this phenomenon normal? I just using the default config.

**Comment by razak17** [comment]
Hi, thanks for trying the plugin. Please make sure to set conceallevel to 2

**Comment by guxuerui** [comment]
> Hi, thanks for trying the plugin. Please make sure to set conceallevel to 2

I confirm that I have set the value of `cenceallevel` to 2 and `concealcusror` to ''. 

And I've noticed that it might be an issue with the `session`. Because if I open the project using `auto-session.nvim`, folding only works in the initially opened file. After switching to other files, folding stops working, and if I clear the session and retry, everything works fine again. Unfortunately, I'm not sure how to resolve this issue...
