### ISSUE TITLE
Breaks with tsx

### ISSUE THREAD

**Issue by ic-768** [razak17/tailwind-fold.nvim#14]
Sometimes it folds non-className attributes. See e.g.  `isBeingEdited={isBeingEdited}`

before:
![image](https://github.com/razak17/tailwind-fold.nvim/assets/83115125/a00cf596-2fa7-4fb4-923b-867063dd0932)

after:
![image](https://github.com/razak17/tailwind-fold.nvim/assets/83115125/bd70befd-addc-4a19-a2c7-8a2fdcf4d84f)

**Comment by razak17** [comment]
This is gonna be tricky to reproduce. Can I get a snippet of the code causing the issue?

**Comment by ic-768** [comment]
> This is gonna be tricky to reproduce. Can I get a snippet of the code causing the issue?

Sure, here's a snippet, but you should know that the behavior is inconsistent. 
It happens in some files, then when I reload vim it stops happening, and eventually I suddenly get the issue in other files.

```
      {isRegionalAdmin && (
        <RegionalAdminControls
          isBeingEdited={isBeingEdited}
          commandBeingIssued={commandBeingIssued}
          setCommandBeingIssued={setCommandBeingIssued}
          onCancel={onCancelEditing}
          toggleIsBeingEdited={toggleIsBeingEdited}
        />
      )}

```
