### ISSUE TITLE
Error using in Lunarvim

### ISSUE THREAD

**Issue by hadnet** [razak17/tailwind-fold.nvim#17]
Tried to install it but does not work. Tried with :TailwindFoldEnable and I got this error:
![Screenshot 2024-10-05 at 12 57 57 PM](https://github.com/user-attachments/assets/dfd2d20f-354b-4b3b-b5b1-d4e63ed0915e)

**Comment by razak17** [comment]
Just tested on a minimal Lunarvim config and I don't get any errors.

Can you update treesitter and try again?
