### ISSUE TITLE
Does not work on block tags

### ISSUE THREAD

**Issue by smsanagustin** [razak17/tailwind-fold.nvim#3]
It doesn't fold HTML classes that are inside of block tags:

```
{% block body %}
        <div class="absolute top-0 left-0 p-10">
           <form action="/upload">
                <button class="relative inline-block px-4 py-2 font-medium group rounded-md">
                    <span class="absolute rounded-md inset-0 w-full h-full transition duration-200 ease-out transform translate-x-1 translate-y-1 bg-black group-hover:-translate-x-0 group-hover:-translate-y-0"></span>
                    <span class="absolute rounded-md inset-0 w-full h-full bg-white border-2 border-black group-hover:bg-black"></span>
                    <span class="relative text-black group-hover:text-white">Go back</span>
                </button>
           </form>
        </div>
{% endblock %}
```

**Comment by razak17** [comment]
Hi, thanks for opening this issue.

Can you provide more info on this issue?

I just tested on a minimal config and it works fine.

A few things to keep in mind:
	- Make sure conceallevel is set to 2.
	- Make sure treesitter parser for html is installed.

**Comment by smsanagustin** [comment]
Treesitter parser for HTML is installed and I've also set conceallevel to 2. The plugin works on normal HTML files. I'm using the lazyvim distribution.

**Comment by razak17** [comment]
I don't use lazyvim so I can test this out right now.

Will try it when I have time and see if I can reproduce this issue.
